syntax on
colorscheme molokai
set t_Co=256
set number
set cursorline
set tabstop=4
set shiftwidth=4
set title
set ruler
set autoindent
set showmatch
set nocompatible
set printoptions=number:y
set incsearch
set iminsert=0
set imsearch=0
set smarttab
set ignorecase
set smartcase
set wildmenu
set encoding=utf-8
set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8,cp932
set fileformats=unix,dos,mac
set showmode
set nobackup
set scrolloff=5
set visualbell t_vb=
set noerrorbells
set backspace=indent,eol,start
set clipboard=unnamed,autoselect
